### ISSUE TITLE
provided .vsix seems faulty

### ISSUE THREAD

**Issue by Tristan2357** [mint-lang/mint-vscode#22]
The .vsix i can download from the marketplace throws this error when instlaling in code-server:
`Corrupt ZIP: end of central directory record signature not found`
I could somehow solve this problem by packaging the extension myself after cloning this repo.

**Comment by gdotdesign** [comment]
Hi, thanks for opening this issue!

I've created a package with `vsce package` per https://code.visualstudio.com/api/working-with-extensions/publishing-extension#usage:

[mint-0.4.0.vsix.zip](https://github.com/mint-lang/mint-vscode/files/6297839/mint-0.4.0.vsix.zip)
(I've zipped it because Github doesn't allow the `.vsix` extension)

Let me know if it works for you!

**Comment by Tristan2357** [comment]
Hi, thanks for the quick reply.

I had the same myself after cloning this repository, which solved the issue for me.
Your provided vsix also worked.

**Comment by gdotdesign** [comment]
Great! Then I'm closing this issue.
